# Pandas (Basic) Exercise

In [1]:
# Todo: import pandas and tqdm modules.
import pandas as pd
from tqdm import tqdm

tickers = ['TSLA', 'MSFT', 'GE']

def get_prices(tickers):
    # Todo: Initialize a DataFrame with a single column 'date'.
    prices_df = pd.DataFrame(columns=['date'])
    
    for ticker in tqdm(tickers):
        # Todo: Read from CSV. Don't forget to use "format".
        df = pd.read_csv("{}.csv".format(ticker))
        
        # Todo: Get column 'date' and 'adjclose'.
        df = df[['date', 'adjclose']]
        
        # Todo: Rename 'adjclose' to ticker name.
        df = df.rename(columns={'adjclose': ticker})
        
        # Todo: Merge `df` into `prices_df`.
        prices_df = prices_df.merge(df, on='date', how='outer')
    
    # Todo: Set 'date' field data type as a proper datetime object.
    prices_df.date = prices_df.date.astype('datetime64[ns]')
    
    # Todo: Sort by date in ascending order.
    prices_df = prices_df.sort_values(by=['date'], ascending=True)
    
    # Todo: Set 'date' object as `prices_df`'s index. 
    prices_df = prices_df.set_index('date')
    return prices_df

In [2]:
# Todo: call get_prices function.
prices_df = get_prices(tickers)
prices_df

100%|██████████| 3/3 [00:00<00:00, 105.79it/s]

              TSLA      MSFT       GE
date
2019-01-02  310.12   99.6466   7.7134
2019-01-03  300.36   95.9808   7.7229
2019-01-04  317.69  100.4448   7.8858
2019-01-07  334.96  100.5729   8.3745
2019-01-08  335.35  101.3021   8.2020
...            ...       ...      ...
2019-10-25  328.13  140.2528   9.0000
2019-10-28  327.71  143.7011   9.0700
2019-10-29  316.22  142.3457   9.0700
2019-10-30  315.01  144.1196  10.1100
2019-10-31  314.92  142.8838   9.9800

[211 rows x 3 columns]

When correct, you should see a result like this:

![pandas-basic answer](media/pandas-basic-answer.png)