# Pandas (Advanced - part 1) Exercise

In [1]:
# Todo: Import pandas
import pandas as pd

df = pd.read_csv("prices.csv")

def get_return_percentages(df):
    # Todo: Shift by one day
    df_shifted = df.shift(1)

    # Todo: Replace the shifted data' first row
    #       with the initial data' first row
    df_shifted.iloc[0, :] = df.iloc[0, :]

    # Todo: Calculate return percentages
    returns = (df - df_shifted) / df_shifted
    return returns

get_return_percentages(df)

         TSLA      MSFT        GE
0    0.000000  0.000000  0.000000
1   -0.031472 -0.036788  0.001232
2    0.057697  0.046509  0.021093
3    0.054361  0.001275  0.061972
4    0.001164  0.007250 -0.020598
..        ...       ...       ...
206  0.094935  0.005645  0.005587
207 -0.001280  0.024586  0.007778
208 -0.035061 -0.009432  0.000000
209 -0.003826  0.012462  0.114664
210 -0.000286 -0.008575 -0.012859

[211 rows x 3 columns]

When correct, you should see the following result:

![pandas adv answer](./media/pandas-adv-answer.png)